"""Change application and rollback infrastructure.

Applies a validated ``ChangeSet`` to disk using ONLY Python filesystem APIs
(`pathlib` / `os`). This layer NEVER uses shell commands, subprocess, or any
command generated by the LLM.

Features:
    - Create and modify files atomically (write temp file + ``os.replace``).
    - Re-reads and verifies the original hash immediately before applying a
      ``modify``; a mismatch aborts the whole transaction.
    - Transaction-like rollback: captures enough information to restore every
      file to its pre-transaction state; on any failure mid-apply all files
      from that transaction are restored.
    - ``dry_run`` mode validates path resolution and state but writes nothing
      and captures no on-disk rollback.
"""

from __future__ import annotations

import hashlib
import logging
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

from rag.config import RagConfig

from backend.domain.change_models import (
    ApplicationResult,
    ChangeSet,
    ChangeOperation,
    RollbackRecord,
)

logger = logging.getLogger(__name__)


class ChangeApplyError(RuntimeError):
    """Base error for change application failures."""


@dataclass(frozen=True)
class ChangeApplier:
    """Apply a validated ChangeSet to a repository within allowed roots."""

    config: RagConfig

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def apply(self, change_set: ChangeSet, *, dry_run: bool = False) -> ApplicationResult:
        """Apply a validated ChangeSet.

        Args:
            change_set: A ChangeSet (should already be validated).
            dry_run: If True, resolve and check target states but never write.

        Returns:
            An ApplicationResult. On failure, all applied files are rolled back
            (unless dry_run, in which case nothing was written anyway).
        """
        if not isinstance(change_set, ChangeSet):
            raise ChangeApplyError("change_set must be a ChangeSet")

        applied_files: list[str] = []
        rollback_records: list[RollbackRecord] = []

        try:
            for change in change_set.changes:
                abs_path = self._resolve_target(change.file_path)
                original_content, original_hash = self._read_current(
                    change, abs_path
                )

                # Verify expected original hash immediately before applying.
                if (
                    change.operation == ChangeOperation.MODIFY
                    and change.original_hash
                    and original_hash != change.original_hash
                ):
                    raise ChangeApplyError(
                        f"original_hash mismatch for {change.file_path}: "
                        "file changed since generation; transaction rejected"
                    )

                # Capture rollback record BEFORE mutating.
                rollback_records.append(
                    RollbackRecord(
                        file_path=str(abs_path),
                        original_content=original_content,
                        original_hash=original_hash,
                        was_created=change.operation == ChangeOperation.CREATE,
                    )
                )

                if dry_run:
                    applied_files.append(change.file_path)
                    continue

                self._write_change(change, abs_path)
                applied_files.append(change.file_path)
                logger.info("ChangeApplier: applied %s %s",
                            change.operation.value, change.file_path)

            return ApplicationResult(
                success=True,
                applied_files=applied_files,
                rollback_records=rollback_records,
                dry_run=dry_run,
            )

        except Exception as exc:
            logger.exception("ChangeApplier: transaction failed, rolling back")
            if not dry_run and rollback_records:
                try:
                    self._rollback(rollback_records)
                except Exception as rollback_exc:
                    logger.exception("ChangeApplier: rollback incomplete")
                    return ApplicationResult(
                        success=False,
                        applied_files=applied_files,
                        rollback_records=rollback_records,
                        dry_run=dry_run,
                        error=f"{exc}; rollback incomplete: {rollback_exc}",
                    )
            return ApplicationResult(
                success=False,
                applied_files=applied_files,
                rollback_records=rollback_records,
                dry_run=dry_run,
                error=str(exc),
            )

    def rollback(self, records: list[RollbackRecord]) -> None:
        """Restore files to their pre-transaction state.

        Raises:
            ChangeApplyError: if any restore step fails.
        """
        self._rollback(records)

    # ------------------------------------------------------------------ #
    # Internals
    # ------------------------------------------------------------------ #

    def _resolve_target(self, file_path: str) -> Path:
        """Return the resolved absolute target path inside an allowed root."""
        if "\\" in file_path or file_path.startswith("/"):
            raise ChangeApplyError(f"unsafe path: {file_path}")
        parts = file_path.split("/")
        if ".." in parts:
            raise ChangeApplyError(f"path traversal not allowed: {file_path}")
        roots = self.config.allowed_repository_roots
        if not roots:
            raise ChangeApplyError("no allowed repository roots configured")
        root = Path(roots[0]).expanduser().resolve()
        target = (root / file_path).resolve()
        if not self.config.is_within_allowed_root(target):
            raise ChangeApplyError(f"target outside allowed root: {file_path}")
        return target

    def _read_current(
        self, change, abs_path: Path
    ) -> tuple[str | None, str | None]:
        """Return (original_content, original_hash) for the current state."""
        if change.operation == ChangeOperation.CREATE:
            if abs_path.exists():
                raise ChangeApplyError(
                    f"cannot create existing path: {change.file_path}"
                )
            return None, None

        # MODIFY
        if not abs_path.exists() or abs_path.is_dir():
            raise ChangeApplyError(
                f"cannot modify missing/dir path: {change.file_path}"
            )
        raw = abs_path.read_bytes()
        try:
            content = raw.decode("utf-8")
        except UnicodeDecodeError:
            content = raw.decode("utf-8", errors="replace")
        return content, hashlib.sha256(raw).hexdigest()

    def _write_change(self, change, abs_path: Path) -> None:
        """Atomically write a file using a temp file + os.replace."""
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        data = change.new_content.encode("utf-8")
        fd, tmp_name = tempfile.mkstemp(dir=str(abs_path.parent), prefix=".wfa_tmp_")
        try:
            with os.fdopen(fd, "wb") as tmp_file:
                tmp_file.write(data)
                tmp_file.flush()
                os.fsync(tmp_file.fileno())
            os.replace(tmp_name, str(abs_path))
        finally:
            if os.path.exists(tmp_name):
                try:
                    os.remove(tmp_name)
                except OSError:  # pragma: no cover
                    logger.warning("failed to remove temp file %s", tmp_name)

    def _rollback(self, records: list[RollbackRecord]) -> None:
        """Restore all recorded files. Created files are removed."""
        errors: list[str] = []
        for record in records:
            try:
                path = Path(record.file_path)
                if record.was_created:
                    if path.exists():
                        _remove_file(path)
                else:
                    if record.original_content is not None:
                        path.parent.mkdir(parents=True, exist_ok=True)
                        _atomic_write(path, record.original_content)
            except Exception as exc:
                logger.exception("rollback failed for %s", record.file_path)
                errors.append(f"{record.file_path}: {exc}")
        if errors:
            raise ChangeApplyError("; ".join(errors))


def _remove_file(path: Path) -> None:
    """Remove a single file (never a directory)."""
    if path.is_dir():
        raise ChangeApplyError(f"refusing to remove directory: {path}")
    # Only file removal via pathlib; no shell, no rm command.
    if path.exists():
        path.unlink()


def _atomic_write(path: Path, content: str) -> None:
    """Atomically write text content to a file."""
    data = content.encode("utf-8")
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=".wfa_roll_")
    try:
        with os.fdopen(fd, "wb") as tmp_file:
            tmp_file.write(data)
            tmp_file.flush()
            os.fsync(tmp_file.fileno())
        os.replace(tmp_name, str(path))
    finally:
        if os.path.exists(tmp_name):
            try:
                os.remove(tmp_name)
            except OSError:  # pragma: no cover
                logger.warning("failed to remove temp file %s", tmp_name)
